[GROG-TECH] new cocktails section
groman00/romanwebnet-gatsby pull request #20
Opened 2021-06-25 19:37 UTC by anneconover

2021-06-25 20:12 UTC, anneconover commented
![image](https://user-images.githubusercontent.com/27318629/123480276-1e1c0a00-d5d0-11eb-953e-ffd2375ff5ab.png)
![image](https://user-images.githubusercontent.com/27318629/123480300-27a57200-d5d0-11eb-92ff-a93220e3cca6.png)

2021-07-09 18:30 UTC, rebeccasiow approved these changes

2021-07-09 18:31 UTC, rebeccasiow commented on src/pages/cocktails/tjs-marg.md
> +- Trader Joes Jalepeno Limeade
jalapeno

2021-07-09 18:31 UTC, rebeccasiow commented on src/pages/cocktails/tjs-marg.md
> +Put limade in cup
yikes

2021-07-09 18:31 UTC, rebeccasiow commented on src/pages/cocktails/tjs-marg.md
> +enjoy
nice

2021-07-09 18:31 UTC, rebeccasiow approved these changes

2021-07-09 18:31 UTC, rebeccasiow commented
so excited for this feature @groman00 !!!! when will this be released????????????

2021-07-09 18:31 UTC, rebeccasiow commented
the romanwebnetizens are WAITING

2021-07-09 18:42 UTC, groman00 commented on src/pages/cocktails/index.tsx
> +    */}
I'm pretty sure i added google analytics somewhere else.  Please delete!

2021-07-09 18:44 UTC, groman00 requested changes
Yea i think cocktails should be a subcategory........

- Recipes
-- Dinners
-- Cocktails
-- Desserts

good luck

2021-07-09 18:51 UTC, rebeccasiow commented
is this an interview question

2021-10-18 19:10 UTC, closed without merging